# Generated by Django 3.0.4 on 2020-12-18 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201218_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraMarcada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Marcado'), (1, 'Concluído'), (2, 'Cancelado')])),
                ('comentario', models.CharField(max_length=500)),
                ('marcado_em', models.DateTimeField(auto_now_add=True)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_atendente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=60)),
                ('tempo_aplicacao', models.IntegerField(default=15, verbose_name='Tempo de aplicação (minutos)')),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Paciente'), (1, 'Profissional'), (2, 'Coordenador do SUS')]),
        ),
        migrations.AlterModelTable(
            name='estabelecimento',
            table='estabelecimento',
        ),
        migrations.CreateModel(
            name='VacinaEstocada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.IntegerField()),
                ('quantidade_atual', models.IntegerField(null=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Estabelecimento')),
                ('hora_marcada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.HoraMarcada')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Vacina')),
            ],
        ),
        migrations.CreateModel(
            name='VacinaAplicada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('hora_marcada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.HoraMarcada')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Vacina')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_abre', models.TimeField()),
                ('hora_fecha', models.TimeField()),
                ('data', models.DateTimeField(null=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Estabelecimento')),
            ],
        ),
        migrations.AddField(
            model_name='horamarcada',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Estabelecimento'),
        ),
        migrations.AddField(
            model_name='horamarcada',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horamarcada',
            name='vacina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Vacina'),
        ),
    ]
