# Generated by Django 3.0.4 on 2020-12-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201218_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacinaestocada',
            name='hora_marcada',
        ),
    ]
