# Generated by Django 3.0.4 on 2020-12-19 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_vacinaestocada_hora_marcada'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacinaestocada',
            name='cadastrado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacinaestocada',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
