# Generated by Django 3.0.4 on 2020-12-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20201219_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horamarcada',
            options={'ordering': ['data']},
        ),
        migrations.AlterField(
            model_name='horamarcada',
            name='status',
            field=models.IntegerField(choices=[(0, 'Marcado'), (1, 'Em atendimento'), (2, 'Cancelado'), (3, 'Concluído')]),
        ),
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado'), (7, 'Domingo')], null=True),
        ),
    ]
