# Generated by Django 3.0.4 on 2020-12-18 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('cnes', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=60)),
                ('endereco', models.TextField()),
            ],
            options={
                'db_table': 'unidade_saude',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('nome', models.CharField(db_column='nome', max_length=30)),
                ('sigla', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('regiao', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('tipo', models.CharField(choices=[('paciente', 'Paciente'), ('profissional', 'Profissional'), ('coordenador', 'Coordenador do SUS')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Estabelecimento')),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('ibge', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Estado')),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Municipio'),
        ),
    ]
